/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-container': '#de8e00',
        'inverse-on-surface': '#eaf1ff',
        'inverse-surface': '#213145',
        'outline': '#71787c',
        'on-secondary-fixed-variant': '#005048',
        'on-primary-fixed': '#001f2a',
        'on-secondary-fixed': '#00201c',
        'on-primary': '#ffffff',
        'secondary': '#3c6376',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4fdbc8',
        'on-tertiary-fixed': '#2a1700',
        'surface-bright': '#f8f9ff',
        'background': '#f8f9ff',
        'surface-container': '#e5eeff',
        'primary-container': '#0d3b4c',
        'error-container': '#ffdad6',
        'surface-variant': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'inverse-primary': '#a4cce1',
        'on-tertiary-fixed-variant': '#653e00',
        'tertiary': '#321d00',
        'on-secondary': '#ffffff',
        'primary-fixed': '#bfe9fe',
        'secondary-fixed': '#71f8e4',
        'surface-tint': '#3c6376',
        'surface': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4f3000',
        'on-background': '#0b1c30',
        'primary': '#006b5f',
        'outline-variant': '#c1c7cc',
        // Darkened one step to reach WCAG AA on surface-container backgrounds (>=4.5:1).
        'on-surface-variant': '#2f3539',
        'primary-fixed-dim': '#a4cce1',
        'tertiary-fixed': '#ffddb8',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'on-primary-container': '#7da5b9',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#224c5d',
        'surface-container-highest': '#d3e4fe',
        'secondary-container': '#6df5e1',
        'on-surface': '#0b1c30',
        'on-secondary-container': '#006f64',
        // Semantic tokens for status UIs so pages stop reaching for raw Tailwind colors.
        'success': '#16A34A',
        'on-success': '#ffffff',
        'success-container': '#dcfce7',
        'on-success-container': '#14532d',
        'warning': '#D97706',
        'on-warning': '#ffffff',
        'warning-container': '#fef3c7',
        'on-warning-container': '#78350f',
        'info': '#2563EB',
        'on-info': '#ffffff',
        'info-container': '#dbeafe',
        'on-info-container': '#1e3a8a',
        // shadcn-style aliases — map to existing MD3 tokens so components using these names work correctly
        'foreground': '#0b1c30',
        'card': '#ffffff',
        'card-foreground': '#0b1c30',
        'border': '#c1c7cc',
        'muted': '#e5eeff',
        'muted-foreground': '#2f3539',
        'primary-foreground': '#ffffff',
        'warning-foreground': '#78350f',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.625rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'gutter': '16px',
        'sidebar-collapsed': '72px',
        'stack-tight': '8px',
        'stack-loose': '20px',
        'container-padding': '24px',
        'base': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['monospace'],
      },
      // Typography scale adapted to dashboard density. Values in rem; letter-spacing matches MD3 type scale.
      fontSize: {
        'display-lg': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-sm': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '700' }],
        'heading-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.005em', fontWeight: '600' }],
        'heading-md': ['1.375rem', { lineHeight: '1.875rem', letterSpacing: '0', fontWeight: '600' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.625rem', letterSpacing: '0', fontWeight: '600' }],
        'title': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.005em', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.005em', fontWeight: '400' }],
        'body': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0.015em', fontWeight: '400' }],
        'caption': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'overline': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.08em', fontWeight: '600' }],
      },
      // Multi-layered shadows with primary tint + inset highlight for glass depth.
      boxShadow: {
        'glass-sm': '0 1px 2px 0 rgba(2,37,50,0.05), 0 0 0 1px rgba(2,37,50,0.04), inset 0 1px 0 0 rgba(255,255,255,0.7)',
        'glass': '0 4px 16px -2px rgba(2,37,50,0.10), 0 0 0 1px rgba(2,37,50,0.05), inset 0 1px 0 0 rgba(255,255,255,0.6)',
        'glass-lg': '0 8px 32px -4px rgba(2,37,50,0.14), 0 0 0 1px rgba(2,37,50,0.06), inset 0 1px 0 0 rgba(255,255,255,0.5)',
        'glass-xl': '0 16px 48px -8px rgba(2,37,50,0.18), 0 0 0 1px rgba(2,37,50,0.07), inset 0 1px 0 0 rgba(255,255,255,0.4)',
        'sm': '0 1px 3px 0 rgba(0,0,0,0.08), 0 1px 2px -1px rgba(0,0,0,0.06)',
        'md': '0 4px 12px -2px rgba(0,0,0,0.10), 0 2px 4px -2px rgba(0,0,0,0.06)',
        'lg': '0 10px 24px -4px rgba(0,0,0,0.12), 0 4px 8px -4px rgba(0,0,0,0.08)',
        'inner': 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
        'none': 'none',
      },
      transitionTimingFunction: {
        'premium': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '500': '500ms',
        '700': '700ms',
      },
      // Layered z-index scale to eliminate ad-hoc z-values across modals, toasts, tooltips.
      zIndex: {
        'base': '0',
        'dropdown': '40',
        'sticky': '50',
        'overlay': '60',
        'modal': '70',
        'popover': '80',
        'toast': '90',
        'tooltip': '100',
      },
      backdropBlur: {
        '4xl': '72px',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(16px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        'bounce-in': {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(8px)' },
          '60%': { opacity: '1', transform: 'scale(1.02) translateY(-2px)' },
          '100%': { transform: 'scale(1) translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 350ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'fade-in-down': 'fade-in-down 350ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'scale-in': 'scale-in 250ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'slide-in-right': 'slide-in-right 350ms cubic-bezier(0.22, 1, 0.36, 1) both',
        'shimmer': 'shimmer 1.6s linear infinite',
        'pulse-soft': 'pulse-soft 2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        'bounce-in': 'bounce-in 500ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
      },
    },
  },
  plugins: [],
}
