/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-container': '#de8e00',
        'inverse-on-surface': '#eaf1ff',
        'inverse-surface': '#213145',
        'outline': '#71787c',
        'on-secondary-fixed-variant': '#005048',
        'on-primary-fixed': '#001f2a',
        'on-secondary-fixed': '#00201c',
        'on-primary': '#ffffff',
        'secondary': '#006b5f',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4fdbc8',
        'on-tertiary-fixed': '#2a1700',
        'surface-bright': '#f8f9ff',
        'background': '#f8f9ff',
        'surface-container': '#e5eeff',
        'primary-container': '#0d3b4c',
        'error-container': '#ffdad6',
        'surface-variant': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'inverse-primary': '#a4cce1',
        'on-tertiary-fixed-variant': '#653e00',
        'tertiary': '#321d00',
        'on-secondary': '#ffffff',
        'primary-fixed': '#bfe9fe',
        'secondary-fixed': '#71f8e4',
        'surface-tint': '#3c6376',
        'surface': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4f3000',
        'on-background': '#0b1c30',
        'primary': '#002532',
        'outline-variant': '#c1c7cc',
        'on-surface-variant': '#41484c',
        'primary-fixed-dim': '#a4cce1',
        'tertiary-fixed': '#ffddb8',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'on-primary-container': '#7da5b9',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#224c5d',
        'surface-container-highest': '#d3e4fe',
        'secondary-container': '#6df5e1',
        'on-surface': '#0b1c30',
        'on-secondary-container': '#006f64',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-width': '260px',
        'gutter': '16px',
        'sidebar-collapsed': '72px',
        'stack-tight': '8px',
        'stack-loose': '20px',
        'container-padding': '24px',
        'base': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['monospace'],
      },
    },
  },
  plugins: [],
}
