import { forwardRef, type HTMLAttributes } from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BadgeIcon,
  Ban,
  Bell,
  Bot,
  Brain,
  BriefcaseBusiness,
  Bug,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle2,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Code2,
  Contact,
  Copy,
  CreditCard,
  Database,
  Edit,
  FileBadge,
  FileCode2,
  FileText,
  Gauge,
  GitBranch,
  Headset,
  History,
  Info,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Link,
  Link2Off,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  MinusCircle,
  Network,
  NotebookText,
  PauseCircle,
  PencilLine,
  PersonStanding,
  PlayCircle,
  Plus,
  QrCode,
  ReceiptText,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldUser,
  Smartphone,
  Sparkles,
  Star,
  Store,
  TerminalSquare,
  TestTube2,
  Trash2,
  TrendingUp,
  SlidersHorizontal,
  User,
  UserMinus,
  UserPlus,
  Users,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from './cn';

export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export interface IconProps extends Omit<HTMLAttributes<SVGSVGElement>, 'children'> {
  name: string;
  size?: IconSize;
  filled?: boolean;
}

const SIZE_CLASS: Record<IconSize, string> = {
  xs: 'h-3.5 w-3.5',
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6',
  xl: 'h-8 w-8',
};

const ICONS: Record<string, LucideIcon> = {
  account_circle: User,
  account_tree: GitBranch,
  add: Plus,
  admin_panel_settings: ShieldUser,
  api: Code2,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  badge: BadgeIcon,
  block: Ban,
  bolt: Zap,
  bug_report: Bug,
  business: Building2,
  calendar_month: CalendarDays,
  cancel: Ban,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  contact_page: Contact,
  contacts: Contact,
  content_copy: Copy,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  data_object: FileCode2,
  database: Database,
  delete: Trash2,
  done_all: CheckCheck,
  edit: Edit,
  edit_note: PencilLine,
  error: AlertCircle,
  error_outline: AlertCircle,
  event: Calendar,
  event_available: CalendarCheck,
  event_note: CalendarRange,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  format_align_left: FileText,
  forum: MessageSquare,
  group: Users,
  help: CircleHelp,
  history: History,
  hub: Network,
  info: Info,
  integration_instructions: TerminalSquare,
  key: KeyRound,
  link: Link,
  link_off: Link2Off,
  lock: Lock,
  lock_open: LockOpen,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  model_training: Workflow,
  notes: NotebookText,
  notifications: Bell,
  pause_circle: PauseCircle,
  payments: CreditCard,
  pending_actions: Clock,
  person: User,
  person_add: UserPlus,
  person_off: UserMinus,
  play_circle: PlayCircle,
  point_of_sale: Landmark,
  progress_activity: RefreshCw,
  psychology: Brain,
  psychology_alt: Brain,
  qr_code: QrCode,
  qr_code_2: QrCode,
  qr_code_scanner: QrCode,
  star: Star,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  remove_moderator: MinusCircle,
  save: Save,
  schedule: Clock,
  science: TestTube2,
  search: Search,
  send: Send,
  settings: Settings,
  shield_person: ShieldUser,
  short_text: FileText,
  smart_toy: Bot,
  smartphone: Smartphone,
  space_dashboard: LayoutDashboard,
  storefront: Store,
  support_agent: Headset,
  timeline: Activity,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  verified_user: ShieldCheck,
  visibility: Circle,
  warning: AlertTriangle,
  workspace_premium: BadgeCheck,
};

export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
  { name, size = 'md', filled: _filled = false, className, 'aria-hidden': ariaHidden, ...rest },
  ref,
) {
  const Lucide = ICONS[name] ?? CircleHelp;

  return (
    <Lucide
      ref={ref}
      aria-hidden={ariaHidden ?? true}
      strokeWidth={2}
      className={cn('inline-block shrink-0', SIZE_CLASS[size], className)}
      {...rest}
    />
  );
});
